[Interface]
Address = 10.13.13.4
PrivateKey = WMV+DK4J4U/tuSXKTDQGUCElp4dt+36aympnqfehD24=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mHX9R6R9XScipV8mfPadH7zywU7wU+EgL2E9qivHIys=
PresharedKey = kuFgQ040j8bBrMLYfwyd0XgTVkzmyrdCFcwkqDsZZpQ=
Endpoint = 192.168.56.101:51820
AllowedIPs = 0.0.0.0/0, ::/0
