[Interface]
Address = 10.13.13.17
PrivateKey = QF6E0J9cY9y/ZlZC5ymq3gmdsfUNfacwF0NP4VwDTGc=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mHX9R6R9XScipV8mfPadH7zywU7wU+EgL2E9qivHIys=
PresharedKey = uxg8ZYH6Anh2bKn1uOS/n1ho9YEG5AI/h7OXvyZ0mnk=
Endpoint = 192.168.56.101:51820
AllowedIPs = 0.0.0.0/0, ::/0
