[Interface]
Address = 10.13.13.8
PrivateKey = 2DXurAHxYH/oVDx5GCDfjV2nOKvDORP5RqCuU2dzkVM=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mHX9R6R9XScipV8mfPadH7zywU7wU+EgL2E9qivHIys=
PresharedKey = RUw6lAXgGJBkmkpTCysfLXghBKM5C71ig4qT7+Bd9YQ=
Endpoint = 192.168.56.101:51820
AllowedIPs = 0.0.0.0/0, ::/0
