[Interface]
Address = 10.13.13.7
PrivateKey = cBzAIZg3L1KWfycxeZ9mCjG8yz1JDCmjgJ0TgWoZd3I=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mHX9R6R9XScipV8mfPadH7zywU7wU+EgL2E9qivHIys=
PresharedKey = pbCo0SbQoZmp5nGYP3gF3wJ1s8cHaBq80d5+KKiMUug=
Endpoint = 192.168.56.101:51820
AllowedIPs = 0.0.0.0/0, ::/0
