[Interface]
Address = 10.13.13.3
PrivateKey = ADgoI7geK7YvR4oaaL5YQFmr4w/52w5bmzXjhyWZF0c=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mHX9R6R9XScipV8mfPadH7zywU7wU+EgL2E9qivHIys=
PresharedKey = tJ29OAN2wa+o9pNcPITSA3cbxYKdfzv8jxb/KX+uQjk=
Endpoint = 192.168.56.101:51820
AllowedIPs = 0.0.0.0/0, ::/0
