[Interface]
Address = 10.13.13.13
PrivateKey = OHewAkxyPydp8ceRO5dT+Hzy5mXQA5J4QazKMRo3z3U=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mHX9R6R9XScipV8mfPadH7zywU7wU+EgL2E9qivHIys=
PresharedKey = uEa2e7YbcfFw+03ARZJu1RaVlFeJdFSjFgwQiijqcbU=
Endpoint = 192.168.56.101:51820
AllowedIPs = 0.0.0.0/0, ::/0
