[Interface]
Address = 10.13.13.12
PrivateKey = mK7yq/sH0GorYZBlv/L+1Xsbb0M38VUIFjbgPHYPy0Q=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mHX9R6R9XScipV8mfPadH7zywU7wU+EgL2E9qivHIys=
PresharedKey = DPqMrFRJiTd3PwbaFE1Ajs++7IN/8pWa/iFMnzwdLDw=
Endpoint = 192.168.56.101:51820
AllowedIPs = 0.0.0.0/0, ::/0
