[Interface]
Address = 10.13.13.16
PrivateKey = kKs1WeRmOmQu/AUY5zOkWgS24ZCAlljN7F9J+UBTB1o=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mHX9R6R9XScipV8mfPadH7zywU7wU+EgL2E9qivHIys=
PresharedKey = v81IKJ4b3anOQ+trfnkloZPDu3hWh5nZhx6uzB11HTc=
Endpoint = 192.168.56.101:51820
AllowedIPs = 0.0.0.0/0, ::/0
