[Interface]
Address = 10.13.13.14
PrivateKey = aL0fsb5kJzJ8XiANIS3+1PioYTMfsIOuXLGvAIkHSnc=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mHX9R6R9XScipV8mfPadH7zywU7wU+EgL2E9qivHIys=
PresharedKey = MMZvqhQ1Jsh/RFK7EuFSUiSE0BGlga+tK8kRNTiVhzc=
Endpoint = 192.168.56.101:51820
AllowedIPs = 0.0.0.0/0, ::/0
