[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = gN+sWHKghlgVdY5mLLEUpzP6ESS8t05JwRXi1+97dnM=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = 5gPGqdnSPT+52Z1QXSdig4VuzKk2TV2IqslX59Gjph0=
PresharedKey = kPWueku5tpA+O0kgQJbCDYV1hxWjhVVHutTi7s9WZPA=
AllowedIPs = 10.13.13.2/32

[Peer]
# peer2
PublicKey = yDRHTju7KBf/UBG9Z8NHsLivYKBjkli0HUCWpkipSkI=
PresharedKey = tJ29OAN2wa+o9pNcPITSA3cbxYKdfzv8jxb/KX+uQjk=
AllowedIPs = 10.13.13.3/32

[Peer]
# peer3
PublicKey = GGBGXWwas6u7+SWYarJeEpMonmL89WKEndGFTIDWJHo=
PresharedKey = kuFgQ040j8bBrMLYfwyd0XgTVkzmyrdCFcwkqDsZZpQ=
AllowedIPs = 10.13.13.4/32

[Peer]
# peer4
PublicKey = Jq2LoWTv0onVA/ixYMZSbXVb+a6QvBytIDs+vNjNcDI=
PresharedKey = d6logccL1r7z2DSh9/t3dqTteiwVBh6tr4fXX3E6mbs=
AllowedIPs = 10.13.13.5/32

[Peer]
# peer5
PublicKey = gVOPjvr+JGzcGSz7F1JfA7/yDSBjsr94+A8+4KbZoEQ=
PresharedKey = +joiIG8XQuIMF+tUjsF2HnPrKsknszXUbliINhyhh7A=
AllowedIPs = 10.13.13.6/32

[Peer]
# peer6
PublicKey = yNnaCHeY34UITfSAffQBZHXO2vV7p5LePxaTSa5X+yQ=
PresharedKey = pbCo0SbQoZmp5nGYP3gF3wJ1s8cHaBq80d5+KKiMUug=
AllowedIPs = 10.13.13.7/32

[Peer]
# peer7
PublicKey = oF5Ck2BwEtl8G6zIoyomEFJyVQsUebP78zwKcLdzmQE=
PresharedKey = RUw6lAXgGJBkmkpTCysfLXghBKM5C71ig4qT7+Bd9YQ=
AllowedIPs = 10.13.13.8/32

[Peer]
# peer8
PublicKey = pzTPBwP+ZC+xPp6h8339NElY3QpX1W267UpclXfCmAI=
PresharedKey = RN4SoM45fzF7IZVHqlaXnMYAHeYc3JjYWQ2R6+gX54g=
AllowedIPs = 10.13.13.9/32

[Peer]
# peer9
PublicKey = VKJJJwH4vfogZHa+Vh/lrITSbS9kQHAc1ROjpaj1/Hk=
PresharedKey = DHNZ18lsJDf7WzF5B/C2ys1Bcsl+KO3NwLfIFdauE+U=
AllowedIPs = 10.13.13.10/32

[Peer]
# peer10
PublicKey = o54z4YnevDYlsVbLd81Uxe1yYVp4Zk4p8WqcfEs5PXE=
PresharedKey = x35gqzV8tHUgxpFkPLRO0v75gv2ggfIH5OkOyt21MS4=
AllowedIPs = 10.13.13.11/32

[Peer]
# peer11
PublicKey = sqodEM9nIMRahYq0u0wf5g/PAOl5OCY3i1w8e4+kEg4=
PresharedKey = DPqMrFRJiTd3PwbaFE1Ajs++7IN/8pWa/iFMnzwdLDw=
AllowedIPs = 10.13.13.12/32

[Peer]
# peer12
PublicKey = pMtjThhdUi/smdhxp8K1Rxc9KYd49NGDszzon6wYsT0=
PresharedKey = uEa2e7YbcfFw+03ARZJu1RaVlFeJdFSjFgwQiijqcbU=
AllowedIPs = 10.13.13.13/32

[Peer]
# peer13
PublicKey = 7aUHWIWhPfm7WEemJjBzEFWWCBJBkP+bnncL9VNP8G8=
PresharedKey = MMZvqhQ1Jsh/RFK7EuFSUiSE0BGlga+tK8kRNTiVhzc=
AllowedIPs = 10.13.13.14/32

[Peer]
# peer14
PublicKey = J50GhFL4w37aFJJWLyVhg45sc7TJI5dQarqs2dA76Ao=
PresharedKey = Ha72e54Gm/y+I9yF8t53/KZ57MOJ/0L0g323sQIXUJk=
AllowedIPs = 10.13.13.15/32

[Peer]
# peer15
PublicKey = kiweUgIz9JuFDjiuFS8xdXzSU3dTpXifZ6UZQz/YYjA=
PresharedKey = v81IKJ4b3anOQ+trfnkloZPDu3hWh5nZhx6uzB11HTc=
AllowedIPs = 10.13.13.16/32

[Peer]
# peer16
PublicKey = zMd6n/1CWJePClOsX8gP3XB2TA7SyEE4lj54orPQuEE=
PresharedKey = uxg8ZYH6Anh2bKn1uOS/n1ho9YEG5AI/h7OXvyZ0mnk=
AllowedIPs = 10.13.13.17/32

[Peer]
# peer17
PublicKey = Gsz+0gEIHvUXB38XOWySZoazv9TggsmXkQyAZqrxhXo=
PresharedKey = p5JFNlWkPbSZsxWowXifo7E4Rqonk+9movxkn/l4rq8=
AllowedIPs = 10.13.13.18/32

[Peer]
# peer18
PublicKey = tsRrbw7UboOvED/Evx6tXQe7VnKjZjSJBZqxFdH/Sng=
PresharedKey = Vikf34QMTpgHFA3MXo0z92f9O+YTAdaDv3wsOAQgk9M=
AllowedIPs = 10.13.13.19/32

[Peer]
# peer19
PublicKey = 1DUMyDdM/1kAOMPS9N+Z8lqkwJsSVaKQA0DI9FP5T2k=
PresharedKey = tzqO0jC/Q4URnpk810DbseJyiDHWHWIXEUJEe8/wrro=
AllowedIPs = 10.13.13.20/32

[Peer]
# peer20
PublicKey = OEmPDRWcxhF+s6bLBb8Zg+xda04a533f39STwwJ/5kI=
PresharedKey = vxTf8xTZyTCKqjt7Q8udTsSJYeUezNplllWLYkNMYhs=
AllowedIPs = 10.13.13.21/32

