[Interface]
Address = 10.13.13.21
PrivateKey = WFuhgyn53yLOzf3GLtiW2FpTjn8KEs7exMLCTKcE0U8=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = mHX9R6R9XScipV8mfPadH7zywU7wU+EgL2E9qivHIys=
PresharedKey = vxTf8xTZyTCKqjt7Q8udTsSJYeUezNplllWLYkNMYhs=
Endpoint = 192.168.56.101:51820
AllowedIPs = 0.0.0.0/0, ::/0
